### ISSUE TITLE
Can't open links that has hashbangs(#!)

### ISSUE THREAD

**Issue by dogancelik** [atom/link#10]
When I try to open this I can't: `http://twitter.com/#!/SomeUsername`

When I click somewhere after `#` (a position after `#`) and do `link:open`, I can't open link.

When I click somewhere before `#` and do `link:open`, it opens link incorrectly: `http://twitter.com/` without including after `#`

2nd example: `https://github.com/#asd/qwe` → `https://github.com/#asd/qwe` (Works!)
3rd example: `https://github.com/#!asd/qwe` → `https://github.com/` (Nope!)
4th example: `https://github.com/asd/qwe#asd` → `https://github.com/asd/qwe#asd` (Works!)

Edit: I'm using Atom v0.194, Win7 64-bit

**Comment by 50Wliu** [comment]
Confirmed on Ubuntu 15.04, latest master.
Seems like link stops recognizing that it's still a valid URL after the !
