### ISSUE TITLE
Command doesn't show up in the keybindings editor

### ISSUE THREAD

**Issue by manuelp** [atom/link#12]
The `link:open` command doesn't show up in the keybindings editor, even if that command is available through the command palette as "Link: Open". I see that the command is [exported](ttps://github.com/atom/link/blob/master/lib/link.coffee#L9) as:

``` coffeescript
atom.commands.add('atom-workspace', 'link:open', openLink)
```

I can change the keybindings manually by editing my `keymap.cson` file, but for some reason that command doesn't show up in the keybindings editor.
## Context
- OS: Kubuntu Linux 14.04.2 LTS (64 bit)
- Atom: 1.0.0
- Link package version: 0.30.0

**Comment by izuzak** [comment]
I'm not sure I understand what you mean by "keybindings editor". Can you share a screenshot of where exactly you expected to see that command?

**Comment by manuelp** [comment]
Yeah, sure. Here is the editor I mentioned as just opened:

![snapshot2](https://cloud.githubusercontent.com/assets/89650/8856920/2bb1d8d2-316e-11e5-8724-0e9def7b5b3c.png)

And here is the results when I search for "Link" (or "link" or anything else related to that):

![snapshot1](https://cloud.githubusercontent.com/assets/89650/8856930/403414aa-316e-11e5-97b0-08ed645fe306.png)

**Comment by izuzak** [comment]
Thanks for clarifying. It shows up on OSX just fine:

![screen shot 2015-07-27 at 00 01 54](https://cloud.githubusercontent.com/assets/38924/8896136/bddb6d5a-33f2-11e5-8c87-a0f307a66308.png)

But you're using Linux, and there's no keybinding for that command on linux:

https://github.com/atom/link/blob/fdddfa0dfa9d0b92f121e4e8f96629fc52ceed18/keymaps/links.cson

The Keybindings section currently shows only commands which have keybindings, it doesn't show commands which don't have keybindings: see https://github.com/atom/settings-view/issues/165.

Also, the Keybindings section isn't an editor -- it's just a viewer currently: https://github.com/atom/settings-view/issues/163. The only way you can change keybindings currently is by editing your keymap.cson file.

So, there are two ways to resolve this issue: add a keybinding for Linux and Windows, or make the Keybindings section show all commands and make it editable.

**Comment by manuelp** [comment]
Understood, thank you very much for the clarifications.

**Comment by phw** [comment]
Any reason, why this does only define a keybinding for OSX? That doesn't make much sense at all, especially as the plugin is advertised as opening links with "ctrl-shift-o", which it just doesn't do by default.

**Comment by 50Wliu** [comment]
This is a larger issue with commands that don't have keybindings not showing up in the Keybindings section of the Settings View and is not specific to the Link package.

See https://github.com/atom/settings-view/issues/165.
