### ISSUE TITLE
Links with underscores get cut off

### ISSUE THREAD

**Issue by jronallo** [atom/link#13]
If any part of an HTTP(s) URL includes an underscore, then everything after the underscore gets cut off from the URL that is opened. For me this includes Google Docs URLs and lots of the local business systems I have to deal with. 

A simple example: https://twitter.com/_
This goes to the twitter home page instead of the profile page for the user @_

**Comment by 50Wliu** [comment]
Unable to confirm.
![link-underscore](https://user-images.githubusercontent.com/2766036/32807850-919f416c-c991-11e7-8d36-a103c77b9d8d.gif)
