### ISSUE TITLE
Cannot open markdown link

### ISSUE THREAD

**Issue by leesei** [atom/link#23]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Cannot open markdown link

### Steps to Reproduce

1. Create markdown file 
```md
[GitBook on GitHub](https://github.com/GitbookIO)
https://github.com/GitbookIO
```
2. hover link in line 1 (character 26 to 49)
3. Trigger "Link:Open" in Command Palette

**Expected behavior:** [What you expect to happen]

Link opened in browser

**Actual behavior:** [What actually happens]

Nothing happened

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

$ atom --version
Atom    : 1.17.2
Electron: 1.4.16
Chrome  : 53.0.2785.143
Node    : 6.5.0

$ apm --version
apm  1.18.2
npm  4.6.1
node 8.0.0 x64
python 2.7.13
git 2.13.0

$ apm ls | grep link
├── link@0.31.3
├── language-hyperlink@0.16.1

### Additional Information

Note bare link in line 2 works

**Comment by rsese** [comment]
> Electron: 1.4.16

Thanks for reaching out!

We've determined that this issue is being caused by the use of an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

**Comment by leesei** [comment]
I see, thanks for the info.

**Comment by leesei** [comment]
I'm on Arch and switch to [aur/atom-editor-bin](https://aur.archlinux.org/packages/atom-editor-bin/), which is based on the Debian release.
The issue persists. Is it still a mismatched versions issue?

$ atom --version
Atom    : 1.17.2
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

$ apm --version
apm  1.17.0
npm  3.10.5
node 6.9.5 x64
python 3.6.1
git 2.13.1

**Comment by rsese** [comment]
> I'm on Arch and switch to aur/atom-editor-bin, which is based on the Debian release.
> The issue persists. Is it still a mismatched versions issue?

Though there might not be version/component mismatches, it's still technically an unofficial - would you be able to install directly from https://atom.io?  Since I don't have Arch setup to test on right now, I'll tag as needs-repro for now.

**Comment by leesei** [comment]
I then downloaded https://github.com/atom/atom/releases/download/v1.17.2/atom-amd64.tar.gz.
I tried to trace the issue by adding `console.log()` to `~/Downloads/atom-1.17.2-amd64/resources/app/node_modules/link/lib` but it there is no output from the console.
```js
    activate: function() {
      console.log('link activated')
      return atom.commands.add('atom-workspace', 'link:open', openLink);
    }
```

Any hint on that?

**Comment by rsese** [comment]
I think if you start in dev mode that should work?

http://flight-manual.atom.io/hacking-atom/sections/contributing-to-official-atom-packages/#running-in-development-mode

**Comment by 50Wliu** [comment]
Cannot confirm, no response:
![markdown-open-link](https://user-images.githubusercontent.com/2766036/32806990-c0e18bd6-c98e-11e7-8bba-f134738acd80.gif)
