### ISSUE TITLE
"ctrl-shift-o" opens "Open Folder" dialog

### ISSUE THREAD

**Issue by dogancelik** [atom/link#9]
In my freshly installed Atom v0.192.0,
Atom Link is enabled by default, yet when I press `ctrl-shift-o`, Atom shows _Open Folder_ dialog.

When I look at the settings, it shows me that `ctrl-shift-O` (mind you, O is capitalized) is binded to `application:open-folder`

I had to open my `keymap.cson` file and add this to make it work:

``` cson
'atom-workspace':
  'ctrl-shift-w': 'link:open'
```

I have Windows 7 (64-bit)

**Comment by kevinsawicki** [comment]
This package only include the `ctrl-shift-o` keybinding on Mac OS X by default.

It doesn't have a default one on Linux or Windows yet.

**Comment by dogancelik** [comment]
I see, a notice to Windows users in package readme would be nice.

**Comment by 50Wliu** [comment]
Better yet would be default Windows/Linux keybindings :wink:.
Is <kbd>Alt+o</kbd> bound to anything?  Nothing's showing up in my keybinding resolver but I do have a bunch of disabled built-in packages.

**Comment by winnetou1357** [comment]
In version 1.0.0 with all build-in packages enabled, `Alt+o` is not bound on Windows, so it seems to be a good choice for default.
Even better, links could be opened not only by a keybinding, but also with a `Ctrl+left click` or similar mouse action, if it is not beyond the scope of this package.

**Comment by dogancelik** [comment]
@winnetou1357 See #6 for <kbd>ctrl+click</kbd>
I think <kbd>Alt+o</kbd> should be default for Win + Linux.

**Comment by murygin** [comment]
Please update the README.md with the current default settings.

**Comment by tafkey** [comment]
+1

**Comment by mateddy** [comment]
On windows, Ctrl-Shift-O bound to "open folder".  This and #16 still has not been fixed??

**Comment by 50Wliu** [comment]
If they were fixed they would be closed.

**Comment by dinesh-v** [comment]
Doesn't work on mac

**Comment by wBureshGitHub** [comment]
Doesn't work on Linux Debian (Jessie, Stretch)

**Comment by dskuya74** [comment]
I added this to my  keymap.cson  file and opens link while in editor and opens "Open Folder" outside of editor window.

'atom-text-editor':
  'ctrl-shift-o': 'link:open'

**Comment by 50Wliu** [comment]
I've changed the package description to no longer reference any keybindings.  It now reads
> Opens the http/https link under the cursor
